# Generated by Django 4.1.4 on 2022-12-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='short_desc',
            field=models.CharField(default='Donec facilisis quam ut purus rutrum lobortis. Donec vitae odio', max_length=200),
            preserve_default=False,
        ),
    ]
